version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    container_name: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  redis:
    image: redis:latest
    restart: always
    command: redis-server --requirepass redispass
    volumes:
      - redis:/data:delegated
    ports:
      - 6379:6379

volumes:
  mongodb_data_container:
  redis: